name: page-build
on:
  page_build

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.9.5"

jobs:
  check-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - name: check status
        run: |
          import os
          status, errormsg = os.getenv('STATUS'), os.getenv('ERROR')
          if status != 'built': raise AssertionError(f"There was an error building the page on GitHub pages.\n\nStatus: {status}\n\nError messsage: {errormsg}")
        shell: python
        env:
          STATUS: ${{ github.event.build.status }}
          ERROR: ${{ github.event.build.error.message }}
